services:
  licence-plate-detection:
    container_name: licence-plate-detection-${BUILD_ENV:-dev}
    image: licence-plate-detection:${BUILD_ENV:-dev}
    build:
      context: ..
      target: ${BUILD_ENV:-dev}
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
    ports:
      - "8888:8888" # For Jupyter notebooks
      - "6006:6006" # For TensorBoard
    networks:
      - licence-plate-detection-network


networks:
  licence-plate-detection-network:
    driver: bridge
