# Environment Configuration
# =======================


#------------------------------------------------------------------------------
# System Paths
#------------------------------------------------------------------------------
paths:
  base_dir: "."
  temp_dir: "/tmp/licence-plate-detection"

#------------------------------------------------------------------------------
# Logging Configuration
#------------------------------------------------------------------------------
logging:
  logger_name: "licence-plate-detection"
  log_level: "info"
  console_logging: true
  file_logging: true

