# Model Configuration
# ===================

#------------------------------------------------------------------------------
# Model Storage
#------------------------------------------------------------------------------
storage:
  storage_dir: "models"
  format: "saved_model"
  version: "v1"

#------------------------------------------------------------------------------
# Model Architecture
#------------------------------------------------------------------------------
architecture:
  optimizer: "adam"
  loss: "sparse_categorical_crossentropy"
  metrics: [ "accuracy" ]


#------------------------------------------------------------------------------
# Model Hyperparameters
#------------------------------------------------------------------------------
hyperparameters:
  hidden_layers: [ 128, 64, 32 ]
  activation: "relu"
  dropout_rate: 0.2
  input_shape: [ 224, 224, 3 ]

#------------------------------------------------------------------------------
# Model Layers
#------------------------------------------------------------------------------
layers:
  conv_blocks:
    first_block:
      filters: [ 64, 64 ]
      kernel_size: [ 3, 3 ]
      pool_size: [ 2, 2 ]
    second_block:
      filters: [ 128, 128 ]
      kernel_size: [ 3, 3 ]
      pool_size: [ 2, 2 ]
    third_block:
      filters: [ 256, 256 ]
      kernel_size: [ 3, 3 ]
      pool_size: [ 2, 2 ]
  dense_layers:
    first_layer:
      units: 512
      dropout_rate: 0.3
