# Training Configuration
# ===================


#------------------------------------------------------------------------------
# Training Parameters
#------------------------------------------------------------------------------
training:
  batch_size: 32
  epochs: 100
  learning_rate: 0.001
  validation_split: 0.2
  early_stopping_patience: 5
  verbose: 1

#------------------------------------------------------------------------------
# Training Metrics
#------------------------------------------------------------------------------
metrics:
  min_accuracy: 0.90
  min_precision: 0.85
  min_recall: 0.85
  min_f1_score: 0.85

#------------------------------------------------------------------------------
# Early Stopping
#------------------------------------------------------------------------------
early_stopping:
  enabled: false
  monitor: "val_loss"
  patience: 10
  verbose: 1
  restore_best_weights: false

#------------------------------------------------------------------------------
# Prediction Settings
#------------------------------------------------------------------------------
prediction:
  batch_processing: true
  timeout_ms: 5000
  return_probabilities: true
  enable_preprocessing: true
  enable_postprocessing: true
  log_predictions: false

#------------------------------------------------------------------------------
# Data Augmentation
#------------------------------------------------------------------------------
data_augmentation:
  horizontal_flip: true
  vertical_flip: true
  rotation_range: 0.1

#------------------------------------------------------------------------------
# Training Data
#------------------------------------------------------------------------------
data:
  data_dir: "data"
  log_dir: "logs"
  preprocessing_workers: 4

